# secIRC Anonymous Messaging Server Configuration

# Network Configuration
network:
  # UDP port for anonymous messaging
  udp_port: 6667
  
  # Maximum packet size (UDP MTU)
  max_packet_size: 1400
  
  # Connection timeout
  connection_timeout: 30
  
  # Maximum concurrent connections
  max_connections: 1000

# Relay Server Configuration
relay:
  # Server identity
  server_id: "auto_generated"  # Will be generated on first run
  
  # Public key for encryption
  public_key: "auto_generated"  # Will be generated on first run
  
  # Private key (encrypted with server password)
  private_key: "auto_generated"  # Will be generated on first run
  
  # Server reputation (0.0 to 1.0)
  initial_reputation: 1.0
  
  # Maximum relay chain length
  max_chain_length: 5
  
  # Message TTL (seconds)
  message_ttl: 300

# Security Configuration
security:
  # Encryption algorithm
  encryption: "AES-256-GCM"
  
  # Key exchange algorithm
  key_exchange: "RSA-2048"
  
  # Message signing
  signing: "RSA-PSS"
  
  # Password hashing
  password_hash: "Argon2id"
  
  # Session timeout
  session_timeout: 3600

# Discovery Configuration
discovery:
  # Enable DNS-based discovery
  dns_discovery: true
  
  # DNS domain for discovery
  dns_domain: "secirc.net"
  
  # Enable web-based discovery
  web_discovery: true
  
  # Web discovery URL
  web_discovery_url: "https://relays.secirc.net/discovery.json"
  
  # Discovery interval (seconds)
  discovery_interval: 300
  
  # Maximum known relays
  max_known_relays: 100

# Logging Configuration
logging:
  # Log level (DEBUG, INFO, WARNING, ERROR, CRITICAL)
  level: "INFO"
  
  # Log file
  log_file: "logs/relay_server.log"
  
  # Maximum log file size (MB)
  max_log_size: 100
  
  # Number of log files to keep
  log_files: 5
  
  # Enable console logging
  console_logging: true

# Performance Configuration
performance:
  # Worker threads
  worker_threads: 4
  
  # Message queue size
  queue_size: 10000
  
  # Batch processing size
  batch_size: 100
  
  # Memory limit (MB)
  memory_limit: 512

# Monitoring Configuration
monitoring:
  # Enable metrics collection
  enable_metrics: true
  
  # Metrics port
  metrics_port: 9090
  
  # Health check endpoint
  health_check: true
  
  # Statistics collection interval
  stats_interval: 60